repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files

-   repo: https://github.com/kevinsawade/pre-commit-hooks
    rev: 0.0.4 # new pushed of my repos are avaialbe as @latest
    hooks:
    -   id: clear-ipynb-cells
